#!/bin/bash

# ========================================
# MANUAL TESTING GUIDE - PHASE 1 USE CASES
# ========================================

echo "========================================"
echo "DAILY WORKER HUB - TESTING GUIDE PHASE 1"
echo "========================================"
echo ""

echo "✅ Use Cases Created for Phase 1:"
echo "========================================"
echo ""
echo "1. CreateJobUseCase"
echo "   - File: domain/usecase/CreateJobUseCase.kt"
echo "   - Validates: wage, worker count, dates, wage type"
echo "   - Tests: valid creation, invalid wage, invalid count, past date"
echo ""
echo "2. ApplyForJobUseCase"
echo "   - File: domain/usecase/ApplyForJobUseCase.kt"
echo "   - Validates: job status, duplicate application, 21 Days Rule"
echo "   - Tests: apply to open, apply to filled, duplicate check, 21 days violation"
echo ""
echo "3. CompleteJobUseCase"
echo "   - File: domain/usecase/CompleteJobUseCase.kt"
echo "   - Validates: job status, job started, hours worked"
echo "   - Tests: complete accepted job, complete without start, invalid hours"
echo ""
echo "4. GetJobDetailsUseCase"
echo "   - File: domain/usecase/GetJobDetailsUseCase.kt"
echo "   - Fetches: job + business + application status"
echo "   - Tests: get by ID, not found, with application"
echo ""

echo "========================================"
echo "DOMAIN MODELS CREATED"
echo "========================================"
echo ""
echo "1. JobRequestModels.kt"
echo "   - CreateJobRequest: create job request with validation"
echo "   - ApplyForJobRequest: apply for job request"
echo "   - CompleteJobRequest: complete job request"
echo ""
echo "2. JobWithDetails.kt"
echo "   - JobWithDetails: job with business info and application status"
echo "   - Helper methods: isJobAvailable, isAcceptingApplications"
echo ""

echo "========================================"
echo "REPOSITORY IMPLEMENTATION CREATED"
echo "========================================"
echo ""
echo "SupabaseJobRepository.kt"
echo "   - Implements JobRepository interface"
echo "   - Methods:"
echo "     ✓ getWorkerProfile()"
echo "     ✓ getWorkerHistory()"
echo "     ✓ getWorkerStats()"
echo "     ✓ getAvailableJobs()"
echo "     ✓ acceptJob(jobId)"
echo "     ✓ getJobById(jobId)"
echo "     ✓ deleteJob(jobId)"
echo "     ✓ createJob(request)"
echo "     ✓ applyForJob(request)"
echo "     ✓ getApplicationById(applicationId)"
echo "     ✓ completeJob(appId, completedAt, hours, amounts)"
echo "     ✓ getJobDetails(jobId)"
echo ""
echo "   - Features:"
echo "     • Supabase REST API integration"
echo "     • Full CRUD operations for jobs and applications"
echo "     • 21 Days Rule compliance checking"
echo "     • Worker statistics calculation"
echo "     • Error handling with logging"
echo ""

echo "========================================"
echo "DATABASE STATUS"
echo "========================================"
echo ""
echo "✅ Dummy Data Already Inserted:"
echo "  • 13 auth users (10 workers + 3 businesses)"
echo "  • 16 profiles (10 workers + 3 businesses + 3 existing)"
echo "  • 12 worker_profiles with location and skills"
echo "  • 4 business_profiles with preferences"
echo "  • 25 jobs with various statuses (open, filled, closed)"
echo "  • 10 job_applications (pending, accepted, completed)"
echo "  • 13 wallets with balances"
echo ""

echo "========================================"
echo "TESTING INSTRUCTIONS"
echo "========================================"
echo ""
echo "📱 Android App Testing:"
echo "========================================"
echo ""
echo "1. Build and Run App"
echo "   ./gradlew assembleDebug"
echo "   adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "2. Test Worker Flow:"
echo "   - Login as worker (test: +628551234567)"
echo "   - Browse jobs (GetJobsForWorkerUseCase)"
echo "   - Apply for job (ApplyForJobUseCase)"
echo "   - Accept application (AcceptJobUseCase - if business)"
echo "   - Complete job (CompleteJobUseCase)"
echo "   - Check stats (GetWorkerStatsUseCase)"
echo ""
echo "3. Test Business Flow:"
echo "   - Login as business (test: warungbali@example.com)"
echo "   - Create job (CreateJobUseCase)"
echo "     • Wage: 150000, worker_count: 2, date: tomorrow"
echo "     • Test validation errors:"
echo "       • Wage: 0 or negative"
echo "       • Worker count: 11 (>10) or 0"
echo "       • End time before start time"
echo "       • Shift date in past"
echo "   - Get applications (GetApplicationsForJobUseCase)"
echo "   - Accept application (AcceptJobUseCase)"
echo "   - View job details (GetJobDetailsUseCase)"
echo ""
echo "4. Test Edge Cases:"
echo "   • Worker apply for same job twice (duplicate)"
echo "   • Worker apply when 21 Days Rule violated (>20 days)"
echo "   • Business cancel job when already filled"
echo "   • Worker complete job before start"
echo "   • Invalid job ID in get details"
echo ""

echo "========================================"
echo "USE CASE VALIDATION MATRIX"
echo "========================================"
echo ""
echo "CreateJobUseCase:"
echo "├─ Valid Input     → Success (201 Created)"
echo "├─ Wage <= 0      → Failure (Validation Error)"
echo "├─ Worker < 1      → Failure (Validation Error)"
echo "├─ Worker > 10     → Failure (Validation Error)"
echo "├─ End ≤ Start    → Failure (Validation Error)"
echo "└─ Past Date       → Failure (Validation Error)"
echo ""
echo "ApplyForJobUseCase:"
echo "├─ Open job       → Success (Pending status)"
echo "├─ Filled job     → Failure (Not available)"
echo "├─ Duplicate       → Failure (Already applied)"
echo "└─ > 20 days      → Failure (21 Days Rule violation)"
echo ""
echo "CompleteJobUseCase:"
echo "├─ Accepted job   → Success (Completed status)"
echo "├─ Not started    → Failure (Job not started)"
echo "├─ Hours ≤ 0      → Failure (Invalid hours)"
echo "└─ Net < 0        → Failure (Invalid payment)"
echo ""

echo "========================================"
echo "NEXT STEPS"
echo "========================================"
echo ""
echo "Phase 2 Use Cases (Priority: High):"
echo "  1. RegisterWorkerUseCase"
echo "  2. RegisterBusinessUseCase"
echo "  3. GetWalletBalanceUseCase"
echo "  4. RequestWithdrawalUseCase"
echo "  5. CheckCompliance21DaysUseCase"
echo "  6. GetApplicationsForJobUseCase"
echo ""
echo "Integration Testing:"
echo "  1. Test complete flow: Worker Register → Browse Jobs → Apply → Accept → Complete"
echo "  2. Test complete flow: Business Register → Create Job → Get Applications → Accept → Complete"
echo "  3. Verify 21 Days Rule blocking works correctly"
echo "  4. Verify payment calculation (6% commission deducted correctly)"
echo ""
echo "========================================"
echo "📊 Summary"
echo "========================================"
echo ""
echo "✅ Phase 1 Complete!"
echo "   • 4 Use Cases implemented"
echo "   • 4 Domain Models created"
echo "   • 1 Repository implementation created"
echo "   • 25 jobs + 10 applications in database"
echo "   • Ready for Android app testing"
echo ""
echo "Total files created: 8"
echo "- domain/usecase/CreateJobUseCase.kt"
echo "- domain/usecase/ApplyForJobUseCase.kt"
echo "- domain/usecase/CompleteJobUseCase.kt"
echo "- domain/usecase/GetJobDetailsUseCase.kt"
echo "- domain/model/JobRequestModels.kt"
echo "- domain/model/JobWithDetails.kt"
echo "- data/repository/SupabaseJobRepository.kt"
echo "- scripts/test-phase-1.sh"
echo ""
echo "========================================"
